# Generated by Django 5.2.9 on 2025-12-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnh', models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('EM_ROTA', 'Em Rota'), ('DISPONIVEL', 'Disponível')], default='DISPONIVEL', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_rota', models.DateField()),
                ('status', models.CharField(default='PLANEJADA', max_length=20)),
                ('km_total_estimado', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('tempo_estimado', models.DurationField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='core.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(max_length=50, unique=True)),
                ('endereco_origem', models.CharField(default='Galpão Principal', max_length=200)),
                ('endereco_destino', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada'), ('REMARCADA', 'Remarcada')], default='PENDENTE', max_length=20)),
                ('capacidade_necessaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateField()),
                ('data_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='core.cliente')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='core.rota')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('VAN', 'Van'), ('CAMINHAO', 'Caminhão')], max_length=20)),
                ('capacidade_maxima', models.DecimalField(decimal_places=2, help_text='Unidades de carga', max_digits=10)),
                ('km_atual', models.DecimalField(decimal_places=1, max_digits=10)),
                ('em_manutencao', models.BooleanField(default=False)),
                ('motorista_ativo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_atual', to='core.motorista')),
            ],
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='core.veiculo'),
        ),
    ]
